author: ['DoctorReid']
planet: '空间站黑塔'
region: '收容舱段'
floor: 1
tp: '控制中心外'
route:
  - op: 'move'
    data: [392, 345]
  - op: 'patrol'
  - op: 'move'
    data: [387, 375]
  - op: 'move'
    data: [397, 435]
  - op: 'move'
    data: [443, 459]
  - op: 'patrol'
  - op: 'move'
    data: [429, 495]
  - op: 'move'
    data: [492, 542]
  - op: 'move'
    data: [555, 546]
  - op: 'move'
    data: [572, 546, 2]
  - op: 'move'
    data: [572, 515]
  - op: 'move'
    data: [610, 515]
  - op: 'patrol'
