author: ['DoctorReid']
planet: '空间站黑塔'
region: '收容舱段'
level: 1
tp: '毁灭之蕾'
route:
  - op: 'move'
    data: [318, 445, -1]
  - op: 'move'
    data: [257, 445]
  - op: 'move'
    data: [257, 325]
  - op: 'move'
    data: [222, 325]
  - op: 'move'
    data: [207, 415]
  - op: 'patrol'