author: ['DoctorReid']
planet: '空间站黑塔'
region: '收容舱段'
floor: 1
tp: '中庭'
route:
  - op: 'move'
    data: [677, 295]
  - op: 'patrol'
  - op: 'move'
    data: [707, 320]
  - op: 'move'
    data: [712, 389]
  - op: 'move'
    data: [696, 436]
  - op: 'move'
    data: [668, 437]
  - op: 'patrol'
