author: ['DoctorReid']
planet: '空间站黑塔'
region: '支援舱段'
floor: 2
tp: '电力室'
route:
  - op: 'move'
    data: [235, 380]
  - op: 'patrol'
  - op: 'move'
    data: [275, 380]
  - op: 'move'
    data: [282, 318]
  - op: 'move'
    data: [322, 312]
  - op: 'patrol'
  - op: 'move'
    data: [448, 312]
  - op: 'move'
    data: [445, 231]
  - op: 'move'
    data: [567, 234]
  - op: 'patrol'
