app_order:
  - 'world_patrol'
  - 'echo_of_war'
  - 'trailblaze_power'
  - 'assignments'
  - 'email'
  - 'support_character'
  - 'nameless_honor'
  - 'daily_training'
  - 'buy_xianzhou_parcel'
  - 'forgotten_hall'
app_run:
  - 'world_patrol'
schedule_hour_1: 'none'
schedule_hour_2: 'none'
