app_order:
  - 'world_patrol'
  - 'assignments'
  - 'email'
  - 'support_character'
  - 'nameless_honor'
  - 'claim_training'
  - 'buy_xianzhou_parcel'
app_run:
  - 'world_patrol'
  - 'assignments'
  - 'email'
  - 'support_character'
  - 'nameless_honor'
  - 'claim_training'
  - 'buy_xianzhou_parcel'
