planet: '空间站黑塔'
region: '收容舱段'
level: 1
tp: '控制中心外'
route:
  - op: 'move'
    data: [392, 340]
  - op: 'patrol'
  - op: 'move'
    data: [387, 370]
  - op: 'move'
    data: [397, 430]
  - op: 'move'
    data: [443, 454]
  - op: 'patrol'
  - op: 'move'
    data: [429, 490]
  - op: 'move'
    data: [492, 537]
  - op: 'move'
    data: [555, 541]
  - op: 'move'
    data: [572, 541, 2]
  - op: 'move'
    data: [572, 510]
  - op: 'move'
    data: [610, 510]
  - op: 'patrol'
