planet: '空间站黑塔'
region: '收容舱段'
level: 1
tp: '中庭'
route:
  - op: 'move'
    data: [670, 280]
  - op: 'patrol'
  - op: 'move'
    data: [700, 305]
  - op: 'move'
    data: [705, 374]
  - op: 'move'
    data: [689, 421]
  - op: 'move'
    data: [661, 422]
  - op: 'patrol'
