planet: '空间站黑塔'
region: '收容舱段'
level: 1
tp: '毁灭之蕾'
route:
  - op: 'move'
    data: [311, 430, -1]
  - op: 'move'
    data: [250, 430]
  - op: 'move'
    data: [250, 310]
  - op: 'move'
    data: [215, 310]
  - op: 'move'
    data: [200, 400]
  - op: 'patrol'