planet: '空间站黑塔'
region: '收容舱段'
level: 1
tp: '毁灭之蕾'
route:
  - op: 'move'
    data: [318, 440, -1]
  - op: 'move'
    data: [257, 440]
  - op: 'move'
    data: [257, 320]
  - op: 'move'
    data: [222, 320]
  - op: 'move'
    data: [207, 410]
  - op: 'patrol'