planet: '空间站黑塔'
region: '收容舱段'
level: 1
tp: '中庭'
route:
  - op: 'move'
    data: [677, 290]
  - op: 'patrol'
  - op: 'move'
    data: [707, 315]
  - op: 'move'
    data: [712, 384]
  - op: 'move'
    data: [696, 431]
  - op: 'move'
    data: [668, 432]
  - op: 'patrol'
