planet: '空间站黑塔'
region: '收容舱段'
level: 1
tp: '控制中心外'
route:
  - op: 'move'
    data: [385, 330]
  - op: 'patrol'
  - op: 'move'
    data: [380, 360]
  - op: 'move'
    data: [390, 420]
  - op: 'move'
    data: [436, 444]
  - op: 'patrol'
  - op: 'move'
    data: [422, 480]
  - op: 'move'
    data: [485, 527]
  - op: 'move'
    data: [558, 531, 2]
  - op: 'move'
    data: [565, 500]
  - op: 'move'
    data: [600, 500]
  - op: 'patrol'
