planet: '仙舟罗浮'
region: '鳞渊境'
level: 0
tp: '古海宫墟'
route:
  - op: 'move'
    data: [1127, 432]
  - op: 'move'
    data: [1127, 453]
  - op: 'move'
    data: [1126, 490]
  - op: 'move'
    data: [1133, 505]
  - op: 'move'
    data: [1143, 523]
  - op: 'move'
    data: [1137, 611]
  - op: 'patrol'
  - op: 'move'
    data: [1087, 609]
  - op: 'move'
    data: [1047, 610]
  - op: 'move'
    data: [1002, 613]
  - op: 'patrol'
  - op: 'move'
    data: [952, 605]
  - op: 'move'
    data: [920, 605]
  - op: 'move'
    data: [920, 624]
  - op: 'move'
    data: [919, 685]
  - op: 'patrol'
  - op: 'move'
    data: [919, 675]
  - op: 'move'
    data: [898, 674]
  - op: 'move'
    data: [886, 674]
  - op: 'move'
    data: [873, 667]
  - op: 'move'
    data: [861, 661]
  - op: 'move'
    data: [852, 650]
  - op: 'move'
    data: [841, 635]
  - op: 'move'
    data: [823, 624]
  - op: 'move'
    data: [803, 610]
  - op: 'move'
    data: [770, 603]
  - op: 'move'
    data: [720, 588]
  - op: 'patrol'
  - op: 'move'
    data: [692, 562]
  - op: 'patrol'
