author: ['DoctorReid', '龙女姬']
planet: '仙舟罗浮'
region: '太卜司'
level: 1
tp: '界寰阵'
route:
  - op: 'move'
    data: [320, 282]
  - op: 'move'
    data: [294, 309]
  - op: 'move'
    data: [288, 390]
  - op: 'move'
    data: [302, 394]
  - op: 'patrol'
  - op: 'move'
    data: [286, 420]
  - op: 'patrol'
  - op: 'move'
    data: [212, 417]
  - op: 'patrol'
  - op: 'move'
    data: [212, 391]
  - op: 'patrol'
  - op: 'move'
    data: [235, 420]
  - op: 'move'
    data: [289, 420]
  - op: 'move'
    data: [289, 520]
  - op: 'move'
    data: [327, 559]
  - op: 'move'
    data: [377, 580]
  - op: 'move'
    data: [404, 635]
  - op: 'move'
    data: [436, 666]
  - op: 'move'
    data: [522, 668]
  - op: 'patrol'
