author: ['DoctorReid', '龙女姬']
planet: '仙舟罗浮'
region: '工造司'
floor: 0
tp: '镕金坊通道'
route:
  - op: 'move'
    data: [793, 589]
  - op: 'move'
    data: [793, 500]
  - op: 'move'
    data: [831, 500]
  - op: 'move'
    data: [896, 502]
  - op: 'move'
    data: [915, 501]
  - op: 'patrol'
  - op: 'move'
    data: [896, 502]
  - op: 'move'
    data: [831, 500]
  - op: 'move'
    data: [798, 500]
  - op: 'move'
    data: [798, 474]
  - op: 'move'
    data: [799, 439]
  - op: 'move'
    data: [779, 430]
  - op: 'move'
    data: [779, 450]
  - op: 'patrol'
  - op: 'move'
    data: [779, 407]
  - op: 'move'
    data: [821, 407]
  - op: 'move'
    data: [869, 407]
  - op: 'move'
    data: [867, 357]
  - op: 'move'
    data: [855, 353]
  - op: 'move'
    data: [858, 305]
  - op: 'move'
    data: [880, 305]
  - op: 'move'
    data: [880, 320]
  - op: 'patrol'
  - op: 'move'
    data: [880, 258]
  - op: 'move'
    data: [802, 258]
  - op: 'move'
    data: [780, 258]
  - op: 'interact'
    data: '入画'
  - op: 'wait'
    data: ['in_world', '20']
  - op: 'update_pos'
    data: [573, 319]
  - op: 'move'
    data: [462, 335]
  - op: 'move'
    data: [415, 337]
  - op: 'patrol'
  - op: 'move'
    data: [413, 370]
  - op: 'patrol'
  - op: 'move'
    data: [408, 406]
  - op: 'move'
    data: [369, 403]
  - op: 'move'
    data: [368, 324]
  - op: 'move'
    data: [348, 329]
  - op: 'patrol'
  - op: 'move'
    data: [343, 392]
  - op: 'patrol'
  - op: 'move'
    data: [346, 427]
  - op: 'patrol'
